<a href="https://colab.research.google.com/github/Sarupriya1998/Data-Science-projects/blob/Python-Numpy-Library/Python_program_using_Numpy_library_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write  a  Python  program  that  takes  the  speeds  of  any  vehicle  to  store  it  in  a NumPy array and calculates the average speed.
Note:Use NumPy functions to get the desired output.

In [ ]:
import numpy as np 
a=int(input("What number of speeds you want to enter?"))
arr=[]
for i in range(a):
  arr.append(float(input("Enter the speeds in Km/hr:")))
arr = np.array(arr) 
avg=np.mean(arr)
print("The Average speed is :",avg,"Km/hr")




What number of speeds you want to enter?5
Enter the speeds in Km/hr:92
Enter the speeds in Km/hr:76
Enter the speeds in Km/hr:83
Enter the speeds in Km/hr:78
Enter the speeds in Km/hr:84
The Average speed is : 82.6 Km/hr


Write a Python program to generate a 3-D array with integers of your choice, perform indexing, and print the first two rows and last two columns of the array.
Note: Use NumPy arange()function to generate a random array

In [ ]:
import numpy as np
arr=np.arange(0,20).reshape(5,4)
print(arr)
print("The first two rows are:")
print(arr[[0,1],:])
print("The last two columns are:")
print(arr[:,[-2,-1]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The first two rows are:
[[0 1 2 3]
 [4 5 6 7]]
The last two columns are:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
